// File generated by FlutterFire CLI.
// Run: flutterfire configure
// PLACEHOLDER - Replace this file by running:
//   dart pub global activate flutterfire_cli
//   flutterfire configure

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web. '
        'Run: flutterfire configure',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
      case TargetPlatform.windows:
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for this platform. '
          'Run: flutterfire configure',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // ⚠️ REPLACE THESE WITH YOUR ACTUAL FIREBASE CONFIG VALUES ⚠️

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCL0n2X-bHmZP4COMeANhJ0wtjZ3WUQ8xk',
    appId: '1:870335404134:android:414beaeb1b795b5dd735a7',
    messagingSenderId: '870335404134',
    projectId: 'todoflow-fccd6',
    storageBucket: 'todoflow-fccd6.firebasestorage.app',
  );

  // Run `flutterfire configure` to generate these automatically.

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDXED8H9C01o-5IiBD72-V8GsyTMEnKKKw',
    appId: '1:870335404134:ios:153e58dca2758e32d735a7',
    messagingSenderId: '870335404134',
    projectId: 'todoflow-fccd6',
    storageBucket: 'todoflow-fccd6.firebasestorage.app',
    iosClientId: '870335404134-fob8b4bjhpgmq5nf25el1eds0teb8u82.apps.googleusercontent.com',
    iosBundleId: 'com.todoapp.todoApp',
  );

}